<?php
use yii\widgets\DetailView;
if($index==0) $template="<tr><th>{label}</th><td>{value}</td></tr>";
else $template="<tr><td>{value}</td></tr>";
?>
<?= DetailView::widget([
    'model' => $model,
    'template' => $template,
    'attributes' => [
        'name',
        'state',
        'grad_rate',
        'grad_rate_men',
        'grad_rate_women',
        'apply_fee',
        [
        'label' => 'Percent Admitted (Total)',
            'value' => $model->pct_adm_ttl,
        ],
        'pct_adm_men',
        'pct_adm_wmen',
        'ugrad_enr',
        [
            'label' => 'Full-time Undergraduate Enrollment ',
            'value' => $model->ft_ugrad_enr,
        ],
        'pt_ugrad_enr',
        'pct_ue_native',
        'pct_ue_asian',
        'pct_ue_black',
        'pct_ue_latino',
        'pct_ue_white',
        'pct_ue_two',
        'pct_ue_unk',
        'pct_fullfirst_any_finaid',
        'avg_fullfirst_loan',
        'pct_fullfirst_loan',
        'avg_fullfirst_oloan',
        'appl_ttl',
        'appl_men',
        'appl_wmen',
        'adm_ttl',
        'adm_men',
        'adm_wmen',
        'sat_cr_25',
        'sat_cr_75',
        'sat_ma_25',
        'sat_ma_75',
        'sat_wr_25',
        'sat_wr_75',
        'act_co_25',
        'act_co_75',
        'act_en_25',
        'act_en_75',
        'act_ma_25',
        'act_ma_75',
        'act_wr_25',
        'act_wr_75',
        'tuition_in',
        'tuition_out',
    ],
]) ?>